version: 2

jobs:
  build:
    working_directory: ~/hooks
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run:
          name: Installing javascript dependencies
          command: yarn install
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Typechecking the source code
          command: yarn typecheck
      - run:
          name: Testing the source code
          command: yarn test:ci

workflows:
  version: 2
  test:
    jobs:
      - build
